<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MetroREX</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <!-- Copiază folderul assets (cu logo.png) lângă .exe la fiecare build -->
  <ItemGroup>
    <None Update="assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
